version: '3'
services:
  web:
    build: .
    ports:
      - 3211:5000
    networks:
      - app_network
  redis:
    image: "redis:alpine"
    ports:
      - 6379:6379
    networks:
      - app_network
networks:
  app_network:
    driver: bridge
